In [1]:
import matplotlib.pyplot as plt 
import pandas as pd

file = "coefficient_file/model-ckpt-8061/w_conv_2 _copy.csv"
# we use it to save our result
file_output_v1 = "coefficient_file/model-ckpt-8061/w_conv_2_v1.csv"
file_output_v2 = "coefficient_file/model-ckpt-8061/w_conv_2_v2.csv"

w_conv_2 = pd.read_csv(file)
w_conv_2.head(10)

   Unnamed: 0         0         1         2         3         4
0         0.0 -0.204706 -0.184845 -0.058542 -0.121374 -0.101874
1         1.0 -0.333089 -0.237278 -0.257839  0.008892 -0.131245
2         2.0 -0.005794 -0.220810 -0.091361 -0.108987 -0.317507
3         3.0 -0.035021 -0.197801 -0.130848 -0.421990 -0.322210
4         4.0  0.317292  0.287020  0.030989 -0.350362 -0.277884
5         NaN  0.000000  1.000000  2.000000  3.000000  4.000000
6         0.0  0.027047  0.112084  0.004819  0.070330  0.020858
7         1.0  0.041194  0.047014 -0.010757  0.052138  0.042763
8         2.0 -0.063975 -0.053063 -0.055774  0.108117 -0.098761
9         3.0 -0.023011  0.020099  0.036335  0.044828  0.026630

In [2]:
# Print the list of the column names
print("index:", w_conv_2.index)
print("columns:", w_conv_2.columns)
# print("values:\n", w_conv_2.values)
print("{} contains {} rows.".format(file, len(w_conv_2.index)))
print("{} contains {} columns.".format(file, w_conv_2.columns.size))
print("data type:\n", w_conv_2.dtypes)
# the dtype of data in column 1
# print("The data type of {} is: {}.".format('"column 1"', w_conv_2["1"].dtype))

index: RangeIndex(start=0, stop=3455, step=1)
columns: Index(['Unnamed: 0', '0', '1', '2', '3', '4'], dtype='object')
coefficient_file/model-ckpt-8061/w_conv_2 _copy.csv contains 3455 rows.
coefficient_file/model-ckpt-8061/w_conv_2 _copy.csv contains 6 columns.
data type:
 Unnamed: 0    float64
0             float64
1             float64
2             float64
3             float64
4             float64
dtype: object

In [3]:
# What are the 10 most frequent values appears in column 0?
state_frequency = w_conv_2["0"].value_counts()
state_frequency.head(10)

 0.000000    575
-0.081134      1
 0.062496      1
-0.270086      1
-0.125714      1
-0.106232      1
-0.012532      1
-0.197963      1
-0.060308      1
-0.026367      1
Name: 0, dtype: int64

delete duplicate rows

In [4]:
import numpy as np
# ranges = np.r_[3:19, 25:30]
# find the duplicate rows [0, 1, 2, 3, 4]
# arrange(start(include), end(not include), step)
ranges = np.arange(5, 3455, 6)
# print("range:\n", ranges)
# delete duplicate rows, inplace=True -> modify the file on disk
w_conv_2.drop(ranges, inplace=True)
w_conv_2.head(10)

    Unnamed: 0         0         1         2         3         4
0          0.0 -0.204706 -0.184845 -0.058542 -0.121374 -0.101874
1          1.0 -0.333089 -0.237278 -0.257839  0.008892 -0.131245
2          2.0 -0.005794 -0.220810 -0.091361 -0.108987 -0.317507
3          3.0 -0.035021 -0.197801 -0.130848 -0.421990 -0.322210
4          4.0  0.317292  0.287020  0.030989 -0.350362 -0.277884
6          0.0  0.027047  0.112084  0.004819  0.070330  0.020858
7          1.0  0.041194  0.047014 -0.010757  0.052138  0.042763
8          2.0 -0.063975 -0.053063 -0.055774  0.108117 -0.098761
9          3.0 -0.023011  0.020099  0.036335  0.044828  0.026630
10         4.0 -0.042360 -0.010961 -0.012949  0.082349 -0.058262

delete duplicate columns

In [5]:
w_conv_2.drop(['Unnamed: 0'], axis=1, inplace=True)
w_conv_2.head(10)

           0         1         2         3         4
0  -0.204706 -0.184845 -0.058542 -0.121374 -0.101874
1  -0.333089 -0.237278 -0.257839  0.008892 -0.131245
2  -0.005794 -0.220810 -0.091361 -0.108987 -0.317507
3  -0.035021 -0.197801 -0.130848 -0.421990 -0.322210
4   0.317292  0.287020  0.030989 -0.350362 -0.277884
6   0.027047  0.112084  0.004819  0.070330  0.020858
7   0.041194  0.047014 -0.010757  0.052138  0.042763
8  -0.063975 -0.053063 -0.055774  0.108117 -0.098761
9  -0.023011  0.020099  0.036335  0.044828  0.026630
10 -0.042360 -0.010961 -0.012949  0.082349 -0.058262

In [6]:
# Index reordering
w_conv_2.index = range(len(w_conv_2))
w_conv_2.head(10)

          0         1         2         3         4
0 -0.204706 -0.184845 -0.058542 -0.121374 -0.101874
1 -0.333089 -0.237278 -0.257839  0.008892 -0.131245
2 -0.005794 -0.220810 -0.091361 -0.108987 -0.317507
3 -0.035021 -0.197801 -0.130848 -0.421990 -0.322210
4  0.317292  0.287020  0.030989 -0.350362 -0.277884
5  0.027047  0.112084  0.004819  0.070330  0.020858
6  0.041194  0.047014 -0.010757  0.052138  0.042763
7 -0.063975 -0.053063 -0.055774  0.108117 -0.098761
8 -0.023011  0.020099  0.036335  0.044828  0.026630
9 -0.042360 -0.010961 -0.012949  0.082349 -0.058262

In [7]:
print("{} contains {} rows.".format(file, len(w_conv_2.index)))
print("{} contains {} columns.".format(file, w_conv_2.columns.size))
w_conv_2.tail(10)

coefficient_file/model-ckpt-8061/w_conv_2 _copy.csv contains 2880 rows.
coefficient_file/model-ckpt-8061/w_conv_2 _copy.csv contains 5 columns.

             0         1         2         3         4
2870  0.086497 -0.063347  0.025803  0.120202 -0.050263
2871  0.104596 -0.042516 -0.047251 -0.085664  0.091939
2872 -0.099702 -0.191310 -0.315814 -0.253643 -0.068269
2873 -0.024454 -0.110599 -0.112775 -0.106312 -0.038206
2874  0.225632  0.158437  0.006593  0.011106  0.024640
2875  0.054751  0.052798 -0.017654  0.056216 -0.227471
2876  0.193267  0.086913 -0.013757 -0.002509 -0.347914
2877 -0.111388 -0.099638 -0.196604 -0.128802 -0.239697
2878 -0.203801 -0.053619 -0.044246 -0.083913 -0.146746
2879 -0.010803  0.091534 -0.225789 -0.243783 -0.116875

#### current_shape=(5 columns * 2880 rows)

every 5 row represent a 2D convolutio kernal

#### target_shape=(25 * 576)

each rows represent a 2D convolution kernel

every 5 row represent a 3D convolutio kernal

In [8]:
# df1 include [0, 5, 10, 15 ... 2875]
# df2 include [1, 6, 11, 16 ... 2876]
# df3 include [2, 7, 12, 17 ... 2877]
# df4 include [3, 8, 13, 18 ... 2878]
# df5 include [4, 9, 14, 19 ... 2879]

# Horizontally connect file 1, file 2, file 3
ranges_df0 = range(0, 2880, 5)
ranges_df1 = range(1, 2880, 5)
ranges_df2 = range(2, 2880, 5)
ranges_df3 = range(3, 2880, 5)
ranges_df4 = range(4, 2880, 5)

#print("ranges_df0:\n", ranges_df0)
#print("ranges_df1:\n", ranges_df1)
#print("ranges_df2:\n", ranges_df2)
#print("ranges_df3:\n", ranges_df3)
#print("ranges_df4:\n", ranges_df4)

# The first parameter is used to select the row
# The second parameter is used to select the column
# df0 = w_conv_2.iloc[ranges_df0, ['0', '1', '2', '3', '4']]
df0 = w_conv_2.iloc[ranges_df0]
df1 = w_conv_2.iloc[ranges_df1]
df2 = w_conv_2.iloc[ranges_df2]
df3 = w_conv_2.iloc[ranges_df3]
df4 = w_conv_2.iloc[ranges_df4]
print(df0.head())
print(df1.head())
print(df2.head())
print(df3.head())
print(df4.head())

           0         1         2         3         4
0  -0.204706 -0.184845 -0.058542 -0.121374 -0.101874
5   0.027047  0.112084  0.004819  0.070330  0.020858
10 -0.212486 -0.402677 -0.287447 -0.003581  0.053766
15 -0.036034  0.016375  0.046564 -0.013529  0.089933
20 -0.052847  0.082417  0.151207 -0.147058  0.132015
           0         1         2         3         4
1  -0.333089 -0.237278 -0.257839  0.008892 -0.131245
6   0.041194  0.047014 -0.010757  0.052138  0.042763
11 -0.443964 -0.230162 -0.108205 -0.043456 -0.089718
16  0.050141 -0.042853 -0.084552 -0.093690 -0.007386
21 -0.125714 -0.036226 -0.092912 -0.004344  0.108049
           0         1         2         3         4
2  -0.005794 -0.220810 -0.091361 -0.108987 -0.317507
7  -0.063975 -0.053063 -0.055774  0.108117 -0.098761
12 -0.224797  0.004448  0.064830  0.064860  0.095063
17  0.097082  0.054257  0.013301  0.123246  0.109932
22 -0.054637 -0.170717 -0.220215 -0.292211 -0.291404
           0         1         2         3         4
3  -0.035021 -0.197801 -0.130848 -0.421990 -0.322210
8  -0.023011  0.020099  0.036335  0.044828  0.026630
13 -0.109704 -0.197341 -0.174878 -0.221539 -0.187418
18 -0.000582 -0.172476 -0.062071  0.086330  0.126036
23 -0.013579  0.106880  0.075826 -0.020418 -0.060992
           0         1         2         3         4
4   0.317292  0.287020  0.030989 -0.350362 -0.277884
9  -0.042360 -0.010961 -0.012949  0.082349 -0.058262
14 -0.040423  0.078379  0.152587  0.081764 -0.169270
19 -0.001751  0.028296 -0.003809 -0.151690  0.023671
24  0.106120  0.115387 -0.056105 -0.000186 -0.009190

In [9]:
# Index reordering
df0.index = range(len(df0))
df1.index = range(len(df1))
df2.index = range(len(df2))
df3.index = range(len(df3))
df4.index = range(len(df4))
print(df0.head())
print(df1.head())
print(df2.head())
print(df3.head())
print(df4.head())

          0         1         2         3         4
0 -0.204706 -0.184845 -0.058542 -0.121374 -0.101874
1  0.027047  0.112084  0.004819  0.070330  0.020858
2 -0.212486 -0.402677 -0.287447 -0.003581  0.053766
3 -0.036034  0.016375  0.046564 -0.013529  0.089933
4 -0.052847  0.082417  0.151207 -0.147058  0.132015
          0         1         2         3         4
0 -0.333089 -0.237278 -0.257839  0.008892 -0.131245
1  0.041194  0.047014 -0.010757  0.052138  0.042763
2 -0.443964 -0.230162 -0.108205 -0.043456 -0.089718
3  0.050141 -0.042853 -0.084552 -0.093690 -0.007386
4 -0.125714 -0.036226 -0.092912 -0.004344  0.108049
          0         1         2         3         4
0 -0.005794 -0.220810 -0.091361 -0.108987 -0.317507
1 -0.063975 -0.053063 -0.055774  0.108117 -0.098761
2 -0.224797  0.004448  0.064830  0.064860  0.095063
3  0.097082  0.054257  0.013301  0.123246  0.109932
4 -0.054637 -0.170717 -0.220215 -0.292211 -0.291404
          0         1         2         3         4
0 -0.035021 -0.197801 -0.130848 -0.421990 -0.322210
1 -0.023011  0.020099  0.036335  0.044828  0.026630
2 -0.109704 -0.197341 -0.174878 -0.221539 -0.187418
3 -0.000582 -0.172476 -0.062071  0.086330  0.126036
4 -0.013579  0.106880  0.075826 -0.020418 -0.060992
          0         1         2         3         4
0  0.317292  0.287020  0.030989 -0.350362 -0.277884
1 -0.042360 -0.010961 -0.012949  0.082349 -0.058262
2 -0.040423  0.078379  0.152587  0.081764 -0.169270
3 -0.001751  0.028296 -0.003809 -0.151690  0.023671
4  0.106120  0.115387 -0.056105 -0.000186 -0.009190

In [10]:
# Splicing files horizontally
w_conv_2_v1 = pd.concat([df0, df1, df2, df3, df4], axis=1)
w_conv_2_v1.head()

,0,1,2,3,4,0,1,2,3,4,...,0,1,2,3,4,0,1,2,3,4
0,-0.204706,-0.184845,-0.058542,-0.121374,-0.101874,-0.333089,-0.237278,-0.257839,0.008892,-0.131245,...,-0.035021,-0.197801,-0.130848,-0.421990,-0.322210,0.317292,0.287020,0.030989,-0.350362,-0.277884
1,0.027047,0.112084,0.004819,0.070330,0.020858,0.041194,0.047014,-0.010757,0.052138,0.042763,...,-0.023011,0.020099,0.036335,0.044828,0.026630,-0.042360,-0.010961,-0.012949,0.082349,-0.058262
2,-0.212486,-0.402677,-0.287447,-0.003581,0.053766,-0.443964,-0.230162,-0.108205,-0.043456,-0.089718,...,-0.109704,-0.197341,-0.174878,-0.221539,-0.187418,-0.040423,0.078379,0.152587,0.081764,-0.169270
3,-0.036034,0.016375,0.046564,-0.013529,0.089933,0.050141,-0.042853,-0.084552,-0.093690,-0.007386,...,-0.000582,-0.172476,-0.062071,0.086330,0.126036,-0.001751,0.028296,-0.003809,-0.151690,0.023671
4,-0.052847,0.082417,0.151207,-0.147058,0.132015,-0.125714,-0.036226,-0.092912,-0.004344,0.108049,...,-0.013579,0.106880,0.075826,-0.020418,-0.060992,0.106120,0.115387,-0.056105,-0.000186,-0.009190

In [11]:
# change the columns name
# print(w_conv_2_v1.columns.values)
# Edit specific columns
# w_conv_2_v1.rename(columns={w_conv_2_v1.columns[0]: "new_name"}, inplace=True)
w_conv_2_v1.columns = ['0','1','2','3','4','5','6','7','8','9','10','11','12','13','14','15',
                       '16','17','18','19','20','21','22','23','24']
print("number of rows:", w_conv_2_v1.index)
w_conv_2_v1.tail()

number of rows: RangeIndex(start=0, stop=576, step=1)

,0,1,2,3,4,5,6,7,8,9,...,15,16,17,18,19,20,21,22,23,24
571,-0.052661,0.002182,0.156837,0.042343,0.010798,0.183754,0.054881,0.061458,0.110218,-0.184316,...,-0.262237,-0.023084,0.020529,-0.013818,-0.055015,0.057782,-0.142328,-0.093126,-0.111813,-0.027610
572,0.030767,0.033132,0.013880,0.037769,0.078906,-0.036203,-0.081067,-0.030439,0.101789,0.069069,...,0.057410,-0.305919,-0.101980,-0.153568,-0.060513,0.118538,0.034702,-0.054407,-0.168059,-0.065171
573,0.041350,0.003551,0.038070,-0.011040,0.076086,-0.056726,-0.041044,-0.040635,-0.103208,0.008620,...,0.002374,-0.131831,-0.035417,-0.157286,0.082486,0.072899,-0.097436,0.026828,0.015734,0.033795
574,0.086497,-0.063347,0.025803,0.120202,-0.050263,0.104596,-0.042516,-0.047251,-0.085664,0.091939,...,-0.024454,-0.110599,-0.112775,-0.106312,-0.038206,0.225632,0.158437,0.006593,0.011106,0.024640
575,0.054751,0.052798,-0.017654,0.056216,-0.227471,0.193267,0.086913,-0.013757,-0.002509,-0.347914,...,-0.203801,-0.053619,-0.044246,-0.083913,-0.146746,-0.010803,0.091534,-0.225789,-0.243783,-0.116875

In [12]:
pd.DataFrame(w_conv_2_v1).to_csv(file_output_v1, index=False)

#### original_shape=(5 columns * 2880 rows)

every 5 row represent a 2D convolutio kernal

#### current_shape=(25 * 576)

each rows represent a 2D convolution kernel

every 5 row represent a 3D convolutio kernal

#### traget_shape=(400 * 36)

each roes represent a 3D convolution kernal

In [13]:
# df_1 include [0, 16, 32, 48 ... 560]
# df_2 include [1, 17, 33, 49 ... 561]
# df_3 include [2, 18, 34, 50 ... 562]
# df_4 include [3, 19, 35, 51 ... 563]
# df_5 include [4, 20, 36, 52 ... 564]

# df_5 include [15, 31, 47, 63 ... 575]
# Horizontally connect file 1, file 2, file 3
ranges_df_0 = range(0, 576, 16)
ranges_df_1 = range(1, 576, 16)
ranges_df_2 = range(2, 576, 16)
ranges_df_3 = range(3, 576, 16)
ranges_df_4 = range(4, 576, 16)
ranges_df_5 = range(5, 576, 16)
ranges_df_6 = range(6, 576, 16)
ranges_df_7 = range(7, 576, 16)
ranges_df_8 = range(8, 576, 16)
ranges_df_9 = range(9, 576, 16)
ranges_df_10 = range(10, 576, 16)
ranges_df_11 = range(11, 576, 16)
ranges_df_12 = range(12, 576, 16)
ranges_df_13 = range(13, 576, 16)
ranges_df_14 = range(14, 576, 16)
ranges_df_15 = range(15, 576, 16)


#print("ranges_df_0:\n", ranges_df_0)
#print("ranges_df_1:\n", ranges_df_1)
#print("ranges_df_2:\n", ranges_df_2)
#print("ranges_df_3:\n", ranges_df_3)
#print("ranges_df_4:\n", ranges_df_4)

# The first parameter is used to select the row
# The second parameter is used to select the column
# df0 = w_conv_2.iloc[ranges_df0, ['0', '1', '2', '3', '4']]
df_0 = w_conv_2_v1.iloc[ranges_df_0]
df_1 = w_conv_2_v1.iloc[ranges_df_1]
df_2 = w_conv_2_v1.iloc[ranges_df_2]
df_3 = w_conv_2_v1.iloc[ranges_df_3]
df_4 = w_conv_2_v1.iloc[ranges_df_4]
df_5 = w_conv_2_v1.iloc[ranges_df_5]
df_6 = w_conv_2_v1.iloc[ranges_df_6]
df_7 = w_conv_2_v1.iloc[ranges_df_7]
df_8 = w_conv_2_v1.iloc[ranges_df_8]
df_9 = w_conv_2_v1.iloc[ranges_df_9]
df_10 = w_conv_2_v1.iloc[ranges_df_10]
df_11 = w_conv_2_v1.iloc[ranges_df_11]
df_12 = w_conv_2_v1.iloc[ranges_df_12]
df_13 = w_conv_2_v1.iloc[ranges_df_13]
df_14 = w_conv_2_v1.iloc[ranges_df_14]
df_15 = w_conv_2_v1.iloc[ranges_df_15]
print(df_0.index)
print(df_1.index)
print(df_2.head())
print(df_3.head())
print(df_4.head())

Int64Index([  0,  16,  32,  48,  64,  80,  96, 112, 128, 144, 160, 176, 192,
            208, 224, 240, 256, 272, 288, 304, 320, 336, 352, 368, 384, 400,
            416, 432, 448, 464, 480, 496, 512, 528, 544, 560],
           dtype='int64')
Int64Index([  1,  17,  33,  49,  65,  81,  97, 113, 129, 145, 161, 177, 193,
            209, 225, 241, 257, 273, 289, 305, 321, 337, 353, 369, 385, 401,
            417, 433, 449, 465, 481, 497, 513, 529, 545, 561],
           dtype='int64')
           0         1         2         3         4         5         6  \
2  -0.212486 -0.402677 -0.287447 -0.003581  0.053766 -0.443964 -0.230162
18 -0.065426 -0.000689 -0.051990  0.027577  0.088194  0.126028 -0.032437
34 -0.190350 -0.202247 -0.196913 -0.115893  0.108501  0.058317  0.035172
50 -0.367895 -0.201100 -0.286316 -0.233650 -0.221754  0.228983  0.163870
66  0.131967  0.156507  0.010483 -0.071357 -0.214854 -0.022440 -0.056677

           7         8         9  ...        15        16        17        18  \
2  -0.108205 -0.043456 -0.089718  ... -0.109704 -0.197341 -0.174878 -0.221539
18 -0.152313  0.008633 -0.214982  ...  0.012474 -0.077949 -0.037723 -0.071548
34  0.167124  0.090586  0.046870  ... -0.152679 -0.214338 -0.364803 -0.210520
50 -0.106752 -0.204822 -0.235940  ...  0.101393  0.080339 -0.027676  0.014052
66 -0.058430 -0.234148 -0.094748  ... -0.120710 -0.321701  0.004876  0.208172

          19        20        21        22        23        24
2  -0.187418 -0.040423  0.078379  0.152587  0.081764 -0.169270
18  0.074025 -0.065504 -0.002288 -0.044839  0.059520  0.041633
34 -0.195978  0.022469  0.066281 -0.042170 -0.018972 -0.050382
50 -0.005693 -0.138608 -0.064776  0.027529  0.042303  0.013729
66  0.171022 -0.280873 -0.088548 -0.018166  0.020242  0.026375

[5 rows x 25 columns]
           0         1         2         3         4         5         6  \
3  -0.036034  0.016375  0.046564 -0.013529  0.089933  0.050141 -0.042853
19 -0.053208 -0.004081  0.028297  0.032798 -0.146703  0.081997 -0.047230
35  0.045133 -0.166877 -0.039894  0.083853  0.072555  0.008246  0.044877
51  0.055242  0.043931 -0.159051 -0.002666  0.225147 -0.053961 -0.201669
67  0.084496  0.020260 -0.014575 -0.019325  0.079902  0.057933  0.058959

           7         8         9  ...        15        16        17        18  \
3  -0.084552 -0.093690 -0.007386  ... -0.000582 -0.172476 -0.062071  0.086330
19 -0.083610 -0.160008  0.030393  ... -0.002038 -0.026281 -0.133787 -0.142579
35  0.107955  0.063802  0.111878  ... -0.164385 -0.137776 -0.070461  0.015693
51 -0.146763 -0.142620  0.163660  ...  0.122255  0.026190  0.099646 -0.015391
67 -0.089345 -0.004759  0.212985  ... -0.099619  0.097849 -0.022117  0.017684

          19        20        21        22        23        24
3   0.126036 -0.001751  0.028296 -0.003809 -0.151690  0.023671
19  0.020844  0.010044 -0.020615 -0.086585 -0.013679 -0.047669
35  0.034338 -0.070263  0.036468 -0.141756  0.005115 -0.031180
51 -0.164112  0.100342  0.118903  0.020862 -0.009527 -0.092020
67 -0.132685  0.118495 -0.121974 -0.109268 -0.004661 -0.065778

[5 rows x 25 columns]
           0         1         2         3         4         5         6  \
4  -0.052847  0.082417  0.151207 -0.147058  0.132015 -0.125714 -0.036226
20 -0.302684 -0.407836 -0.414499 -0.131163  0.033878 -0.330578 -0.102717
36 -0.107459  0.047851  0.089668 -0.015012 -0.223831 -0.020788  0.098702
52  0.139216  0.043782  0.081824  0.042905 -0.258236 -0.023425  0.011611
68 -0.010773 -0.038479 -0.437312 -0.219601 -0.047349 -0.033595 -0.145913

           7         8         9  ...        15        16        17        18  \
4  -0.092912 -0.004344  0.108049  ... -0.013579  0.106880  0.075826 -0.020418
20  0.136940  0.125611  0.184951  ... -0.032770  0.016872 -0.069972 -0.031093
36 -0.231906 -0.272672 -0.084667  ...  0.204547  0.173256  0.153511  0.038078
52 -0.005424  0.021724 -0.229649  ...  0.035932 -0.048551 -0.275104 -0.260811
68 -0.050513 -0.123671 -0.261040  ...  0.014535  0.085394  0.028758 -0.052726

          19        20        21        22        23        24
4  -0.060992  0.106120  0.115387 -0.056105 -0.000186 -0.009190
20 -0.132456 -0.016711  0.039738  0.081748 -0.090325  0.022766
36 -0.153694 -0.080160 -0.094345 -0.068247 -0.269674 -0.081689
52 -0.071370 -0.029060 -0.110909 -0.170106 -0.167952  0.104847
68 -0.003153  0.204576 -0.195947 -0.203891 -0.098712 -0.055822

[5 rows x 25 columns]

In [14]:
# Index reordering
df_0.index = range(len(df_0))
df_1.index = range(len(df_1))
df_2.index = range(len(df_2))
df_3.index = range(len(df_3))
df_4.index = range(len(df_4))
df_5.index = range(len(df_5))
df_6.index = range(len(df_6))
df_7.index = range(len(df_7))
df_8.index = range(len(df_8))
df_9.index = range(len(df_9))
df_10.index = range(len(df_10))
df_11.index = range(len(df_11))
df_12.index = range(len(df_12))
df_13.index = range(len(df_13))
df_14.index = range(len(df_14))
df_15.index = range(len(df_15))

print(df_0.index)
print(df_0.head())
print(df_1.head())
print(df_2.head())
print(df_3.head())
print(df_4.head())

RangeIndex(start=0, stop=36, step=1)
          0         1         2         3         4         5         6  \
0 -0.204706 -0.184845 -0.058542 -0.121374 -0.101874 -0.333089 -0.237278
1 -0.056844 -0.209696 -0.088802  0.063549  0.043175 -0.072592 -0.327112
2  0.065327  0.160564 -0.011977  0.095787 -0.041801  0.075102  0.028978
3  0.187503 -0.023920 -0.230681 -0.112892 -0.056581  0.018375 -0.092272
4 -0.095971 -0.135152 -0.029347 -0.018842 -0.062037 -0.150597 -0.133287

          7         8         9  ...        15        16        17        18  \
0 -0.257839  0.008892 -0.131245  ... -0.035021 -0.197801 -0.130848 -0.421990
1 -0.022000 -0.026903  0.032087  ... -0.111496 -0.025667  0.033313  0.040611
2  0.114581  0.011071 -0.137743  ... -0.023084  0.103199 -0.035807  0.051809
3 -0.189669 -0.149256 -0.248318  ... -0.041468 -0.147520  0.136170  0.304206
4 -0.285940 -0.285609 -0.113527  ... -0.166281  0.210562  0.115688  0.210496

         19        20        21        22        23        24
0 -0.322210  0.317292  0.287020  0.030989 -0.350362 -0.277884
1  0.169776  0.025875 -0.014430  0.136193  0.201377 -0.047148
2 -0.201673 -0.037033  0.031500  0.185381  0.162263 -0.165052
3  0.156643 -0.103524  0.058663  0.170046 -0.019313 -0.072780
4 -0.044468  0.063276 -0.190296 -0.053784  0.275983  0.012989

[5 rows x 25 columns]
          0         1         2         3         4         5         6  \
0  0.027047  0.112084  0.004819  0.070330  0.020858  0.041194  0.047014
1  0.045699  0.066054  0.067441  0.079145  0.005859  0.033896  0.024477
2 -0.048100 -0.013767 -0.006192 -0.033437  0.029712  0.102467  0.085036
3  0.092295  0.028490 -0.004488  0.054604  0.060995 -0.121722 -0.060314
4 -0.039394  0.062268  0.125556  0.003800  0.049057 -0.024665 -0.002732

          7         8         9  ...        15        16        17        18  \
0 -0.010757  0.052138  0.042763  ... -0.023011  0.020099  0.036335  0.044828
1  0.028367  0.022084 -0.059181  ...  0.009009 -0.076056 -0.167011 -0.143767
2 -0.039862  0.078924  0.034854  ...  0.073180  0.147253  0.020921  0.031910
3 -0.099373  0.107477  0.018608  ...  0.007175  0.041520 -0.093320 -0.209206
4  0.120716  0.005751  0.059625  ...  0.028540 -0.124308 -0.060416 -0.026451

         19        20        21        22        23        24
0  0.026630 -0.042360 -0.010961 -0.012949  0.082349 -0.058262
1 -0.010528  0.003460 -0.156425 -0.097033 -0.073994 -0.047380
2  0.054527  0.033811 -0.044926 -0.027492 -0.015615  0.022424
3  0.108933  0.086214  0.024877 -0.055956  0.004400  0.115615
4 -0.049053 -0.067495 -0.078394 -0.092859 -0.068667 -0.052783

[5 rows x 25 columns]
          0         1         2         3         4         5         6  \
0 -0.212486 -0.402677 -0.287447 -0.003581  0.053766 -0.443964 -0.230162
1 -0.065426 -0.000689 -0.051990  0.027577  0.088194  0.126028 -0.032437
2 -0.190350 -0.202247 -0.196913 -0.115893  0.108501  0.058317  0.035172
3 -0.367895 -0.201100 -0.286316 -0.233650 -0.221754  0.228983  0.163870
4  0.131967  0.156507  0.010483 -0.071357 -0.214854 -0.022440 -0.056677

          7         8         9  ...        15        16        17        18  \
0 -0.108205 -0.043456 -0.089718  ... -0.109704 -0.197341 -0.174878 -0.221539
1 -0.152313  0.008633 -0.214982  ...  0.012474 -0.077949 -0.037723 -0.071548
2  0.167124  0.090586  0.046870  ... -0.152679 -0.214338 -0.364803 -0.210520
3 -0.106752 -0.204822 -0.235940  ...  0.101393  0.080339 -0.027676  0.014052
4 -0.058430 -0.234148 -0.094748  ... -0.120710 -0.321701  0.004876  0.208172

         19        20        21        22        23        24
0 -0.187418 -0.040423  0.078379  0.152587  0.081764 -0.169270
1  0.074025 -0.065504 -0.002288 -0.044839  0.059520  0.041633
2 -0.195978  0.022469  0.066281 -0.042170 -0.018972 -0.050382
3 -0.005693 -0.138608 -0.064776  0.027529  0.042303  0.013729
4  0.171022 -0.280873 -0.088548 -0.018166  0.020242  0.026375

[5 rows x 25 columns]
          0         1         2         3         4         5         6  \
0 -0.036034  0.016375  0.046564 -0.013529  0.089933  0.050141 -0.042853
1 -0.053208 -0.004081  0.028297  0.032798 -0.146703  0.081997 -0.047230
2  0.045133 -0.166877 -0.039894  0.083853  0.072555  0.008246  0.044877
3  0.055242  0.043931 -0.159051 -0.002666  0.225147 -0.053961 -0.201669
4  0.084496  0.020260 -0.014575 -0.019325  0.079902  0.057933  0.058959

          7         8         9  ...        15        16        17        18  \
0 -0.084552 -0.093690 -0.007386  ... -0.000582 -0.172476 -0.062071  0.086330
1 -0.083610 -0.160008  0.030393  ... -0.002038 -0.026281 -0.133787 -0.142579
2  0.107955  0.063802  0.111878  ... -0.164385 -0.137776 -0.070461  0.015693
3 -0.146763 -0.142620  0.163660  ...  0.122255  0.026190  0.099646 -0.015391
4 -0.089345 -0.004759  0.212985  ... -0.099619  0.097849 -0.022117  0.017684

         19        20        21        22        23        24
0  0.126036 -0.001751  0.028296 -0.003809 -0.151690  0.023671
1  0.020844  0.010044 -0.020615 -0.086585 -0.013679 -0.047669
2  0.034338 -0.070263  0.036468 -0.141756  0.005115 -0.031180
3 -0.164112  0.100342  0.118903  0.020862 -0.009527 -0.092020
4 -0.132685  0.118495 -0.121974 -0.109268 -0.004661 -0.065778

[5 rows x 25 columns]
          0         1         2         3         4         5         6  \
0 -0.052847  0.082417  0.151207 -0.147058  0.132015 -0.125714 -0.036226
1 -0.302684 -0.407836 -0.414499 -0.131163  0.033878 -0.330578 -0.102717
2 -0.107459  0.047851  0.089668 -0.015012 -0.223831 -0.020788  0.098702
3  0.139216  0.043782  0.081824  0.042905 -0.258236 -0.023425  0.011611
4 -0.010773 -0.038479 -0.437312 -0.219601 -0.047349 -0.033595 -0.145913

          7         8         9  ...        15        16        17        18  \
0 -0.092912 -0.004344  0.108049  ... -0.013579  0.106880  0.075826 -0.020418
1  0.136940  0.125611  0.184951  ... -0.032770  0.016872 -0.069972 -0.031093
2 -0.231906 -0.272672 -0.084667  ...  0.204547  0.173256  0.153511  0.038078
3 -0.005424  0.021724 -0.229649  ...  0.035932 -0.048551 -0.275104 -0.260811
4 -0.050513 -0.123671 -0.261040  ...  0.014535  0.085394  0.028758 -0.052726

         19        20        21        22        23        24
0 -0.060992  0.106120  0.115387 -0.056105 -0.000186 -0.009190
1 -0.132456 -0.016711  0.039738  0.081748 -0.090325  0.022766
2 -0.153694 -0.080160 -0.094345 -0.068247 -0.269674 -0.081689
3 -0.071370 -0.029060 -0.110909 -0.170106 -0.167952  0.104847
4 -0.003153  0.204576 -0.195947 -0.203891 -0.098712 -0.055822

[5 rows x 25 columns]

In [15]:
# Splicing files horizontally
w_conv_2_v2 = pd.concat([df_0, df_1, df_2, df_3, df_4, df_5, df_6, df_7, df_8, df_9, df_10,
                         df_11, df_12, df_13, df_14, df_15], axis=1)
w_conv_2_v2.tail(15)

,0,1,2,3,4,5,6,7,8,9,...,15,16,17,18,19,20,21,22,23,24
21,-0.102462,0.037964,-0.171212,-0.136496,-0.034893,0.088701,-0.033780,-0.104119,-0.105936,-0.069978,...,-0.081134,-0.136423,-0.198023,-0.206267,-0.051855,0.029202,-0.054671,-0.234491,-0.028132,0.026136
22,-0.054082,0.030083,0.046394,-0.129693,0.144561,-0.047178,0.026596,0.104296,0.057134,0.170520,...,0.085632,0.108315,-0.314490,0.114617,0.115706,0.084678,0.112379,-0.132998,0.081218,0.016178
23,-0.121831,-0.191514,-0.121123,0.050817,0.010022,-0.049707,-0.157727,0.131236,0.180580,0.107901,...,-0.006139,-0.142983,-0.086450,-0.003293,0.143691,-0.109723,-0.316916,-0.275277,-0.047534,-0.044881
24,-0.252484,0.076681,0.087456,0.103911,-0.139274,-0.127413,-0.155260,-0.238562,-0.195514,-0.213669,...,0.042526,-0.051951,-0.019028,-0.049674,0.055737,0.147588,-0.118247,-0.061023,0.073342,-0.042278
25,-0.002624,0.015155,-0.003625,0.036051,0.096031,-0.106232,0.031366,0.090160,0.319059,0.208281,...,-0.018939,-0.022292,0.177741,-0.085776,-0.157849,0.147478,-0.009494,0.101069,-0.098399,-0.246998
26,-0.019200,-0.070073,0.000974,0.067476,-0.012631,-0.013944,-0.067854,0.184205,0.073022,-0.107373,...,-0.166397,0.050186,0.036121,-0.045905,-0.236709,0.020698,-0.184061,-0.325383,-0.088548,-0.047710
27,0.096723,-0.086420,-0.089216,0.177118,-0.027940,0.098496,0.013147,0.037274,-0.050981,-0.069318,...,0.105823,0.055999,0.046820,-0.083661,0.005893,-0.151913,0.051553,0.054098,-0.136787,0.158255
28,0.298791,0.185255,0.029265,-0.067767,-0.204622,0.158270,0.160698,-0.129327,-0.006519,-0.076843,...,-0.110652,-0.026548,0.033485,-0.125093,-0.199579,-0.220381,-0.042813,-0.039711,-0.016346,0.044604
29,-0.139279,-0.147906,-0.121708,-0.016224,0.187565,-0.211766,-0.286898,-0.139353,0.065698,0.194239,...,-0.096148,-0.251115,-0.287975,-0.224155,-0.028279,0.149892,-0.004396,-0.139367,-0.119517,0.123958
30,-0.119359,-0.151920,-0.105854,-0.098343,-0.012138,0.036500,0.047854,0.122303,0.020416,-0.003929,...,0.132505,0.083086,-0.104882,-0.018694,0.078889,-0.129944,-0.145208,-0.210860,0.013475,0.029762
31,0.139434,0.092182,-0.127441,-0.136506,-0.131861,0.071289,0.002136,-0.100486,-0.250839,-0.272320,...,0.202751,-0.015208,0.295003,0.261225,0.027994,-0.150877,0.168323,0.102135,0.083886,-0.020069
32,-0.331060,-0.131893,-0.063073,0.180129,0.131753,-0.081923,-0.079446,-0.064572,0.063696,0.119063,...,-0.194229,-0.068202,-0.195704,-0.357845,-0.380514,-0.123323,-0.146651,-0.292629,-0.327261,-0.109988
33,0.015082,-0.057234,0.059219,-0.005388,-0.028387,-0.010823,0.031478,-0.004602,-0.024968,0.142511,...,0.261304,-0.005754,0.139498,0.189390,0.027867,0.115372,-0.010502,0.075761,0.117899,0.001400
34,0.089134,-0.056189,-0.074762,0.145890,-0.056078,-0.079387,-0.097860,-0.195529,-0.115951,0.002081,...,0.154761,-0.036034,0.133414,0.037572,-0.124111,-0.188742,0.212918,0.258991,0.073620,-0.002837
35,-0.058467,-0.013060,-0.022886,-0.195604,-0.116399,0.066474,0.036997,-0.157725,-0.043704,-0.092467,...,-0.203801,-0.053619,-0.044246,-0.083913,-0.146746,-0.010803,0.091534,-0.225789,-0.243783,-0.116875

In [16]:
# change the columns name to 0->399
# print(w_conv_2_v2.columns.values)
# Edit specific columns
# w_conv_2_v2.rename(columns={w_conv_2_v1.columns[0]: "new_name"}, inplace=True)
ranges_columns_name_v2 = range(0, 400, 1)
w_conv_2_v2.columns = ranges_columns_name_v2
print("number of rows:", w_conv_2_v2.index)
w_conv_2_v2.tail()

number of rows: RangeIndex(start=0, stop=36, step=1)

,0,1,2,3,4,5,6,7,8,9,...,390,391,392,393,394,395,396,397,398,399
31,0.139434,0.092182,-0.127441,-0.136506,-0.131861,0.071289,0.002136,-0.100486,-0.250839,-0.272320,...,0.202751,-0.015208,0.295003,0.261225,0.027994,-0.150877,0.168323,0.102135,0.083886,-0.020069
32,-0.331060,-0.131893,-0.063073,0.180129,0.131753,-0.081923,-0.079446,-0.064572,0.063696,0.119063,...,-0.194229,-0.068202,-0.195704,-0.357845,-0.380514,-0.123323,-0.146651,-0.292629,-0.327261,-0.109988
33,0.015082,-0.057234,0.059219,-0.005388,-0.028387,-0.010823,0.031478,-0.004602,-0.024968,0.142511,...,0.261304,-0.005754,0.139498,0.189390,0.027867,0.115372,-0.010502,0.075761,0.117899,0.001400
34,0.089134,-0.056189,-0.074762,0.145890,-0.056078,-0.079387,-0.097860,-0.195529,-0.115951,0.002081,...,0.154761,-0.036034,0.133414,0.037572,-0.124111,-0.188742,0.212918,0.258991,0.073620,-0.002837
35,-0.058467,-0.013060,-0.022886,-0.195604,-0.116399,0.066474,0.036997,-0.157725,-0.043704,-0.092467,...,-0.203801,-0.053619,-0.044246,-0.083913,-0.146746,-0.010803,0.091534,-0.225789,-0.243783,-0.116875

In [17]:
pd.DataFrame(w_conv_2_v2).to_csv(file_output_v2, index=False)